POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "NLW IA",
  "details": "Um evento para quem é apaxionado por programação",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/b45032ed-2a3c-4c0d-9215-dece1acec822/attendees
Content-Type: application/json

{
  "name": "Roberto Carlos",
  "email": "robertianhao@gmail.com"
}

###

GET http://localhost:3333/events/b45032ed-2a3c-4c0d-9215-dece1acec822/attendees

###

GET http://localhost:3333/events/c7a86a3c-7433-4d8e-ac97-3854d8c41975

###

GET http://localhost:3333/attendees/3/badge

###

GET http://localhost:3333/attendees/3/check-in